const en = {
    playM: "Start playing online with a guest code",
    inputCodeM: "Type the code here",
    oM: "or",
    selectNivel1M: "Create the game",
    selectNivel2M: "Easy",
    selectNivel3M: "Half",
    selectNivel4M: "Hard",
    play1M: "How do you want the cards?",
    play11M: "Automatic selection",
    play12M: "Manual selection",
    play121M: "Remains to choose",
    play2M: "How do you want to play?",
    play21M: "1 Player",
    play22M: "2 Players (online)",
    intentosM: "Attempts:",
    abandonarM: "Abort?",
    abandonar1M: "Do you want to leave the game ☹️?",
    siM: "YES",
    noM: "NO",
    tituloIngM: "Login",
    loginM: "Login",
    loginInput1M: "Type email",
    loginInput2M: "Type password",
    loginBotonM: "Login",
    loginBoton2M: "Logging in...",
    sinCuentaM: "Don't have an account?",
    registrarseM: "Sign up",
    tituloRegM: "Sign up",
    registroM: "Sign up",
    registroInput1M: "Type a email",
    registroInput2M: "Set your password",
    registroBotonM: "Sign up",
    registroBoton2M: "Signing up...",
    conCuentaM: "Already have an account?",
    conLoginM: "Login",
    cerrarSeM: "Do you want to log out of ",
    alertnoconex1M: "Server unavailable",
    alertnoconex2M: "Sorry! Currently not possible to set up plays online, please try again later...",
    alertnoconex3M: "Connection error",
    alertcodigoinva1M: "Invalid code ",
    alertcodigoinva2M: "Please check and try again",
    alertcodigoinva3M: "Back",
    showcodigocopyM: "Code copied ",
    anfitrionM: "Host ",
    invitadoM: "Guest ",
    playAnfitrionM: "Host  turn",
    playInvitadoM: "Guess turn",
    felicidadesM: "🎉Congratulations🎉 you have made it in ",
    felicidades1M: " attempts",
    invitadoAbanM: "Guest left the game",
    anfitrionAbanM: "Host left the game",
    crearPartidaM: "CREATE NEW GAME",
    ganaAnfitrionM: "🎉🎉Win Host🎉🎉",
    ganaInvitadoM: "🎉🎉Win Guest🎉🎉",
    empateM: "🎉🎉 Tie 🎉🎉",
    generaCodigoM: "Generating code, please wait...",
    iniciaPartiM: "Starting game, please wait...",
    compartaCodigoM: "Share this code with your guest",
    partidaNuevaM: "Start a new game",
    minM: " Min ",
    secM: " Sec ",
    sesiontM: "Important information",
    sesionmM: "To create online play, must be login or register with an email 😁",
    alertnoconex11M: "Email error",
    alertnoconex12M: "Empty or invalid email field",
    alertnoconex22M: "Email format error",
    alertnoconex21M: "You have entered an invalid email",
    alertnoconex33M: "Email does not exist",
    alertnoconex31M: "There is no user record that corresponds to the email provided",
    alertnoconex44M: "Invalid password",
    alertnoconex41M: "Wrong password, please check and try again",
    alertnoconex55M: "Suspended account",
    alertnoconex51M: "Your account is disabled, you must contact App support",
    alertnoconex66M: "Access temporarily blocked",
    alertnoconex61M: "Access to this account has been temporarily disabled due to many failed login attempts. You can try again later",
    alertnoconex77M: "Email in use",
    alertnoconex71M: "The email is already registered",
    alertnoconex88M: "Weak password",
    alertnoconex81M: "Password is very weak, you must use at least 6 characters",
    olvidoemailM: "I forgot the passwod",
    olvidoemail1M: "Access recovery",
    olvidoemail2M: "A password change link will be sent to ",
    olvidoemail3M: "Send recovery",
    olvidoemail4M: "Cancel",
    olvidoemail5M: "Email field must not be empty",
    olvidoemail6M: "You must type the email to recover",
    olvidoemail7M: "Email sent",
    olvidoemail8M: "Password recovery email was sent successfully, if you don't see it in your inbox, please check your spam",
    alertactualizar1M: "Game Update",
    alertactualizar2M: "A new updated version of the game is available",
    alertactualizar3M: "Update now",
    alertactualizar4M: "Later",
    alertactualizar5M: "Alert",
    invitacionappM: "MemojiGame | I invite you to play memory online, download it here from the Google Play Store  ",
    invitacionapp1M: "Share",
    registrarse1M: "Sign up",
    tengocuentaM: "I already have an account"
}
const es = {
    playM: "Juega en línea con código de Invitado",
    inputCodeM: "Agrega el código aquí",
    oM: "o",
    selectNivel1M: "Crea la partida",
    selectNivel2M: "Fácil",
    selectNivel3M: "Medio",
    selectNivel4M: "Dificil",
    play1M: "¿Como desea las cartas?",
    play11M: "Selección automática",
    play12M: "Selección manual",
    play121M: "Resta por elegir",
    play2M: "¿Cómo desea jugar?",
    play21M: "1 Jugador",
    play22M: "2 Jugadores (En línea)",
    intentosM: "Intentos:",
    abandonarM: "¿Abandonar?",
    abandonar1M: "¿Desea abandonar la partida ☹️?",
    siM: "SI",
    noM: "NO",
    tituloIngM: "Ingresar",
    loginM: "Ingresar",
    loginInput1M: "Introduzca email",
    loginInput2M: "Introduzca contraseña",
    loginBotonM: "Ingresar",
    loginBoton2M: "Ingresando...",
    sinCuentaM: "¿No tienes cuenta?",
    registrarseM: "Registrarse",
    tituloRegM: "Registrarse",
    registroM: "Registro",
    registroInput1M: "Introduzca un email",
    registroInput2M: "Establezca su contraseña",
    registroBotonM: "Registrarse",
    registroBoton2M: "Registrando...",
    conCuentaM: "¿Ya tienes cuenta?",
    conLoginM: "Ingresar",
    cerrarSeM: "¿Desea cerrar sesión de ",
    alertnoconex1M: "Servidor no disponible",
    alertnoconex2M: "En estos momentos no es posible establecer partidas en línea, por favor intente más tarde...",
    alertnoconex3M: "Error de conexión",
    alertcodigoinva1M: "Codigo invalido ",
    alertcodigoinva2M: "Verifiquelo e intente nuevamente",
    alertcodigoinva3M: "Volver",
    showcodigocopyM: "Código copiado ",
    anfitrionM: "Anfitrión ",
    invitadoM: "Invitado ",
    playAnfitrionM: "Juega Anfitrión",
    playInvitadoM: "Juega  Invitado",
    felicidadesM: "🎉Felicidades🎉 lo has logrado en ",
    felicidades1M: " intentos",
    invitadoAbanM: "Invitado abandono la partida",
    anfitrionAbanM: "Anfitrión abandono la partida",
    crearPartidaM: "CREAR NUEVA PARTIDA",
    ganaAnfitrionM: "🎉🎉Gana Anfitrión🎉🎉",
    ganaInvitadoM: "🎉🎉Gana Invitado🎉🎉",
    empateM: "🎉🎉 Empate 🎉🎉",
    generaCodigoM: "Generando código, por favor espere...",
    iniciaPartiM: "Iniciando partida, por favor espere...",
    compartaCodigoM: "Comparta este código con su invitado",
    partidaNuevaM: "Crear nueva partida",
    minM: " Min ",
    secM: " Seg ",
    sesiontM: "Información Importante",
    sesionmM: "Para crear partidas en línea, se requiere iniciar sesión o registrarse con un correo electrónico 😁",
    alertnoconex11M: "Error con email",
    alertnoconex12M: "Campo email vacio o invalido",
    alertnoconex22M: "Error con formato de email",
    alertnoconex21M: "Ha introducido un email invalido",
    alertnoconex33M: "Email no existe",
    alertnoconex31M: "No existe ningún registro de usuario que corresponda al email proporcionado",
    alertnoconex44M: "Contraseña invalida",
    alertnoconex41M: "Contraseña incorrecta, verifique e intente nuevamente",
    alertnoconex55M: "Cuenta suspendida",
    alertnoconex51M: "Su cuenta se encuentra inhabilitada, debe contactar a soporte App",
    alertnoconex66M: "Acceso bloqueado temporalmente",
    alertnoconex61M: "El acceso a esta cuenta se ha inhabilitado temporalmente debido a muchos intentos fallidos de inicio de sesión. Puede volver a intentarlo más tarde",
    alertnoconex77M: "Email en uso",
    alertnoconex71M: "El email ya se encuentra registrado",
    alertnoconex88M: "Contraseña debil",
    alertnoconex81M: "Contraseña es muy debil, debe utilizar 6 caracteres como mínimo",
    olvidoemailM: "Olvide Contraseña",
    olvidoemail1M: "Recuperación de acceso",
    olvidoemail2M: "Se enviará un enlace para cambio de contraseña a ",
    olvidoemail3M: "Enviar recuperación",
    olvidoemail4M: "Cancelar",
    olvidoemail5M: "Campo email vacio",
    olvidoemail6M: "Debe introducir el email a recuperar",
    olvidoemail7M: "Correo Enviado",
    olvidoemail8M: "Se envió correo de recuperación de contraseña correctamente, si no lo ve en su bandeja de entrada, por favo revise su correo no deseado",
    alertactualizar1M: "Actualización de Juego",
    alertactualizar2M: "Se detectó una nueva versión actualizada del juego",
    alertactualizar3M: "Actualizar ahora",
    alertactualizar4M: "Después",
    alertactualizar5M: "Alerta",
    invitacionappM: "MemojiGame | Te invito a jugar memoria en línea, descargalo aquí desde Google Play Store  ",
    invitacionapp1M: "Compartir",
    registrarse1M: "Registrarme",
    tengocuentaM: "Ya tengo cuenta"
}
const hi = {
    playM: "अतिथि कोड के साथ ऑनलाइन खेलना प्रारंभ करें",
    inputCodeM: "यहां कोड टाइप करें",
    oM: "या",
    selectNivel1M: "खेल बनाएँ",
    selectNivel2M: "आसान",
    selectNivel3M: "उदारवादी",
    selectNivel4M: "मुश्किल",
    play1M: "आप कार्ड कैसे चाहते हैं?",
    play11M: "स्वचालित चयन",
    play12M: "मैनुअल चयन",
    play121M: "चुनना बाकी है",
    play2M: "आप कैसे खेलना चाहते हैं?",
    play21M: "1 खिलाड़ी",
    play22M: "2 खिलाड़ी (ऑनलाइन)",
    intentosM: "प्रयास",
    abandonarM: "निरस्त करें?",
    abandonar1M: "क्या आप खेल छोड़ना चाहते हैं ☹️?",
    siM: "हाँ",
    noM: "नहीं",
    tituloIngM: "लॉग इन करें",
    loginM: "लॉग इन करें",
    loginInput1M: "ईमेल टाइप करें",
    loginInput2M: "पासवर्ड लिखें",
    loginBotonM: "लॉग इन करें",
    loginBoton2M: "प्रवेश किया",
    sinCuentaM: "खाता नहीं है?",
    registrarseM: "साइन अप करें",
    tituloRegM: "साइन अप करें",
    registroM: "साइन अप करें",
    registroInput1M: "एक ईमेल टाइप करें",
    registroInput2M: "अपना पासवर्ड निर्धारित करें",
    registroBotonM: "साइन अप करें",
    registroBoton2M: "साइन उप हो रहा है",
    conCuentaM: "क्या आपके पास पहले से एक खाता मौजूद है?",
    conLoginM: "लॉग इन करें",
    cerrarSeM: "क्या आप लॉग आउट करना चाहते हैं ",
    alertnoconex1M: "सर्वर अनुपलब्ध",
    alertnoconex2M: "क्षमा मांगना! वर्तमान में नाटकों को ऑनलाइन सेट अप करना संभव नहीं है, कृपया बाद में पुनः प्रयास करें",
    alertnoconex3M: "संपर्क त्रुटि",
    alertcodigoinva1M: "अवैध कोड ",
    alertcodigoinva2M: "कृपया जाँच करें और पुनः प्रयास करें",
    alertcodigoinva3M: "पीछे",
    showcodigocopyM: "कोड कॉपी किया गया ",
    anfitrionM: "मेज़बान ",
    invitadoM: "अनुमान ",
    playAnfitrionM: "मेजबान की बारी",
    playInvitadoM: "अनुमान    बारी",
    felicidadesM: "🎉बधाई🎉",
    felicidades1M: " प्रयास",
    invitadoAbanM: "अतिथि ने खेल छोड़ दिया",
    anfitrionAbanM: "मेजबान ने खेल छोड़ दिया",
    crearPartidaM: "नया गेम बनाएं",
    ganaAnfitrionM: "🎉🎉जीत मेजबान🎉🎉",
    ganaInvitadoM: "🎉🎉विन अतिथि🎉🎉",
    empateM: "🎉🎉 बाँधना 🎉🎉",
    generaCodigoM: "कोड जनरेट कर रहा है, कृपया प्रतीक्षा करें",
    iniciaPartiM: "गेम प्रारंभ हो रहा है, कृपया प्रतीक्षा करें",
    compartaCodigoM: "इस कोड को अपने अतिथि के साथ साझा करें",
    partidaNuevaM: "एक नया खेल शुरू करें",
    minM: " मिनट ",
    secM: " सेकंड",
    sesiontM: "महत्वपूर्ण सूचना",
    sesionmM: "ऑनलाइन खेल बनाने के लिए लॉगिन या एक ईमेल के साथ रजिस्टर होना चाहिए 😁",
    alertnoconex11M: "ईमेल त्रुटि",
    alertnoconex12M: "खाली या अमान्य ईमेल फ़ील्ड",
    alertnoconex22M: "ईमेल प्रारूप त्रुटि",
    alertnoconex21M: "आपने एक अमान्य ईमेल दर्ज किया है",
    alertnoconex33M: "ईमेल मौजूद नहीं है",
    alertnoconex31M: "प्रदान किए गए ईमेल से संबंधित कोई उपयोगकर्ता रिकॉर्ड नहीं है",
    alertnoconex44M: "अवैध पासवर्ड",
    alertnoconex41M: "गलत पासवर्ड, कृपया जांचें और पुनः प्रयास करें",
    alertnoconex55M: "निलंबित खाता",
    alertnoconex51M: "आपका खाता अक्षम कर दिया गया है, आपको ऐप समर्थन से संपर्क करना होगा",
    alertnoconex66M: "पहुंच अस्थायी रूप से अवरुद्ध है",
    alertnoconex61M: "कई विफल लॉगिन प्रयासों के कारण इस खाते तक पहुंच अस्थायी रूप से अक्षम कर दी गई है। आप देर से पुनः प्रयास कर सकते हैंr",
    alertnoconex77M: "ईमेल उपयोग में है",
    alertnoconex71M: "ईमेल पहले से पंजीकृत है",
    alertnoconex88M: "कमजोर पासवर्ड",
    alertnoconex81M: "पासवर्ड बहुत कमजोर है, आपको कम से कम 6 अक्षरों का उपयोग करना चाहिए",
    olvidoemailM: "मैं पासवर्ड भूल गया",
    olvidoemail1M: "पहुँच पुनर्प्राप्ति",
    olvidoemail2M: "पासवर्ड बदलने का लिंक भेजा जाएगा ",
    olvidoemail3M: "वसूली भेजें",
    olvidoemail4M: "रद्द करना",
    olvidoemail5M: "ईमेल फ़ील्ड खाली नहीं होनी चाहिए",
    olvidoemail6M: "पुनर्प्राप्त करने के लिए आपको ईमेल टाइप करना होगा",
    olvidoemail7M: "ईमेल भेजा",
    olvidoemail8M: "पासवर्ड पुनर्प्राप्ति ईमेल सफलतापूर्वक भेजा गया था, यदि आप इसे अपने इनबॉक्स में नहीं देखते हैं, तो कृपया अपना स्पैम जांचें",
    alertactualizar1M: "गेम अपडेट",
    alertactualizar2M: "खेल का एक नया अद्यतन संस्करण उपलब्ध है",
    alertactualizar3M: "अभी अद्यतन करें",
    alertactualizar4M: "बाद में",
    alertactualizar5M: "चेतावनी",
    invitacionappM: "MemojiGame | मैं आपको स्मृति ऑनलाइन खेलने के लिए आमंत्रित करता हूं, इसे यहां Google Play Store से डाउनलोड करें  ",
    invitacionapp1M: "शेयर करना",
    registrarse1M: "साइन अप करें",
    tengocuentaM: "मेरा पहले से ही खाता है"
}
const zh = {
    playM: "開始新遊戲",
    inputCodeM: "在此處輸入代碼",
    oM: "或者",
    selectNivel1M: "創建遊戲",
    selectNivel2M: "簡單的",
    selectNivel3M: "緩和",
    selectNivel4M: "難的",
    play1M: "你要怎樣的卡片？",
    play11M: "自動選擇",
    play12M: "手動選擇",
    play121M: "仍有選擇",
    play2M: "你想怎麼玩？",
    play21M: "1名球員",
    play22M: "2 名玩家（在線）",
    intentosM: "嘗試",
    abandonarM: "中止？",
    abandonar1M: "你想離開遊戲嗎 ☹️?",
    siM: "是的",
    noM: "不",
    tituloIngM: "登錄",
    loginM: "登錄",
    loginInput1M: "輸入電子郵件",
    loginInput2M: "輸入密碼",
    loginBotonM: "登錄",
    loginBoton2M: "在登錄",
    sinCuentaM: "沒有帳戶？",
    registrarseM: "報名",
    tituloRegM: "報名",
    registroM: "報名",
    registroInput1M: "輸入電子郵件",
    registroInput2M: "設置你的密碼",
    registroBotonM: "報名",
    registroBoton2M: "報名",
    conCuentaM: "已有帳戶？",
    conLoginM: "登錄",
    cerrarSeM: "你想退出嗎",
    alertnoconex1M: "服務器無法使用",
    alertnoconex2M: "對不起！目前無法在線設置播放，請稍後重試",
    alertnoconex3M: "連接錯誤",
    alertcodigoinva1M: "無效的代碼",
    alertcodigoinva2M: "請檢查並重試",
    alertcodigoinva3M: "後退",
    showcodigocopyM: "代碼已復制",
    anfitrionM: "主持人",
    invitadoM: "客人",
    playAnfitrionM: "主機轉",
    playInvitadoM: "猜轉",
    felicidadesM: "🎉恭喜你🎉",
    felicidades1M: "嘗試",
    invitadoAbanM: "客人離開遊戲",
    anfitrionAbanM: "主持人退出遊戲",
    crearPartidaM: "創建新遊戲",
    ganaAnfitrionM: "🎉🎉贏得主人🎉🎉",
    ganaInvitadoM: "🎉🎉贏得客人🎉🎉",
    empateM: "🎉🎉 領帶 🎉🎉",
    generaCodigoM: "正在生成代碼，請稍候",
    iniciaPartiM: "開始遊戲，請稍候",
    compartaCodigoM: "與您的客人分享此代碼",
    partidaNuevaM: "開始新遊戲",
    minM: " 分鐘 ",
    secM: " 秒",
    sesiontM: "重要信息",
    sesionmM: "要創建在線遊戲，必須登錄或使用電子郵件註冊 😁",
    alertnoconex11M: "電子郵件錯誤",
    alertnoconex12M: "空的或無效的電子郵件字段",
    alertnoconex22M: "郵件格式錯誤",
    alertnoconex21M: "您輸入了無效的電子郵件",
    alertnoconex33M: "電子郵件不存在",
    alertnoconex31M: "沒有與提供的電子郵件對應的用戶記錄",
    alertnoconex44M: "無效的密碼",
    alertnoconex41M: "密碼錯誤，請檢查並重試",
    alertnoconex55M: "暫停的帳戶",
    alertnoconex51M: "您的帳戶已被禁用，您必須聯繫應用支持",
    alertnoconex66M: "訪問暫時被阻止",
    alertnoconex61M: "由於多次登錄嘗試失敗，對該帳戶的訪問已被暫時禁用。你可以稍後再試",
    alertnoconex77M: "使用中的電子郵件",
    alertnoconex71M: "該郵箱已經註冊",
    alertnoconex88M: "密碼強度低",
    alertnoconex81M: "密碼很弱，您必須至少使用 6 個字符",
    olvidoemailM: "我忘記了密碼",
    olvidoemail1M: "訪問恢復",
    olvidoemail2M: "密碼更改鏈接將發送至 ",
    olvidoemail3M: "發送恢復",
    olvidoemail4M: "取消",
    olvidoemail5M: "電子郵件字段不能為空",
    olvidoemail6M: "您必須輸入電子郵件才能恢復",
    olvidoemail7M: "郵件已發送",
    olvidoemail8M: "密碼恢復郵件發送成功，如果您沒有在收件箱中看到它，請檢查您的垃圾郵件",
    alertactualizar1M: "遊戲更新",
    alertactualizar2M: "遊戲的新更新版本可用",
    alertactualizar3M: "現在更新",
    alertactualizar4M: "之後",
    alertactualizar5M: "警報",
    invitacionappM: "MemojiGame | 我邀請你在線玩記憶，從 Google Play 商店下載它  ",
    invitacionapp1M: "分享",
    registrarse1M: "報名",
    tengocuentaM: "我已經有一個帳戶"
}
const pt = {
    playM: "Comece a jogar online com um código de convidado",
    inputCodeM: "Digite o código aqui",
    oM: "ou",
    selectNivel1M: "Crie o jogo",
    selectNivel2M: "Fácil",
    selectNivel3M: "Moderado",
    selectNivel4M: "Duro",
    play1M: "Como você quer as cartas?",
    play11M: "Seleção automática",
    play12M: "Seleção manual",
    play121M: "Resta escolher",
    play2M: "Como você quer jogar?",
    play21M: "1 Jogador",
    play22M: "2 jogadores (on-line)",
    intentosM: "Tentativas",
    abandonarM: "Abortar?",
    abandonar1M: "Quer sair do jogo ☹️?",
    siM: "SIM",
    noM: "NÃO",
    tituloIngM: "Conecte-se",
    loginM: "Conecte-se",
    loginInput1M: "Digite e-mail",
    loginInput2M: "Digite a senha",
    loginBotonM: "Conecte-se",
    loginBoton2M: "Fazendo login",
    sinCuentaM: "Não tem uma conta?",
    registrarseM: "Inscrever-se",
    tituloRegM: "Inscrever-se",
    registroM: "Inscrever-se",
    registroInput1M: "Digite um e-mail",
    registroInput2M: "Coloque sua senha",
    registroBotonM: "Inscrever-se",
    registroBoton2M: "Inscrever-se",
    conCuentaM: "já tem uma conta?",
    conLoginM: "Conecte-se",
    cerrarSeM: "Deseja sair?",
    alertnoconex1M: "Servidor indisponível",
    alertnoconex2M: "Desculpe! Atualmente não é possível configurar jogadas online, tente novamente mais tarde",
    alertnoconex3M: "Erro de conexão",
    alertcodigoinva1M: "Código inválido",
    alertcodigoinva2M: "Por favor verifique e tente novamente",
    alertcodigoinva3M: "voltar",
    showcodigocopyM: "Código copiado",
    anfitrionM: "Anfitrião",
    invitadoM: "Convidado",
    playAnfitrionM: "Turno do anfitrião",
    playInvitadoM: "Turno do Convidado",
    felicidadesM: "🎉Parabéns🎉",
    felicidades1M: "voltas",
    invitadoAbanM: "Convidado saiu do jogo",
    anfitrionAbanM: "Anfitrião saiu do jogo",
    crearPartidaM: "CRIAR NOVO JOGO",
    ganaAnfitrionM: "🎉🎉Ganhar Anfitrião🎉🎉",
    ganaInvitadoM: "🎉🎉Ganhar Convidado🎉🎉",
    empateM: "🎉🎉 Emparelhado 🎉🎉",
    generaCodigoM: "Gerando código, aguarde",
    iniciaPartiM: "Iniciando o jogo, aguarde",
    compartaCodigoM: "Compartilhe este código com seu convidado",
    partidaNuevaM: "Iniciar um novo jogo",
    minM: " Min ",
    secM: " Seg",
    sesiontM: "Informação importante",
    sesionmM: "PPara criar jogo online, deve ser login ou registrar-se com um e-mail 😁",
    alertnoconex11M: "erro de e-mail",
    alertnoconex12M: "Campo de e-mail vazio ou inválido",
    alertnoconex22M: "Erro de formato de e-mail",
    alertnoconex21M: "Você digitou um e-mail inválido",
    alertnoconex33M: "e-mail não existe",
    alertnoconex31M: "Não existe registo de utilizador que corresponda ao email fornecido",
    alertnoconex44M: "Senha inválida",
    alertnoconex41M: "Senha incorreta, verifique e tente novamente",
    alertnoconex55M: "Conta suspensa",
    alertnoconex51M: "Sua conta está desativada, você deve entrar em contato com o suporte do aplicativo",
    alertnoconex66M: "Acesso temporariamente bloqueado",
    alertnoconex61M: "O acesso a esta conta foi temporariamente desativado devido a muitas tentativas de login malsucedidas. Você pode tentar novamente mais tarde",
    alertnoconex77M: "E-mail em uso",
    alertnoconex71M: "O e-mail já está cadastrado",
    alertnoconex88M: "senha fraca",
    alertnoconex81M: "A senha é muito fraca, você deve usar pelo menos 6 caracteres",
    olvidoemailM: "Esqueci a senha",
    olvidoemail1M: "Recuperação de acesso",
    olvidoemail2M: "Um link de alteração de senha será enviado para ",
    olvidoemail3M: "Enviar recuperação",
    olvidoemail4M: "Cancelar",
    olvidoemail5M: "O campo de e-mail não deve estar vazio",
    olvidoemail6M: "Você deve digitar o e-mail para recuperar",
    olvidoemail7M: "E-mail enviado",
    olvidoemail8M: "O e-mail de recuperação de senha foi enviado com sucesso, se você não o vir em sua caixa de entrada, verifique seu spam",
    alertactualizar1M: "atualização do jogo",
    alertactualizar2M: "Uma nova versão atualizada do jogo está disponível",
    alertactualizar3M: "Atualizar agora",
    alertactualizar4M: "Mais tarde",
    alertactualizar5M: "Alerta",
    invitacionappM: "MemojiGame | Convido você a jogar memória online, baixe aqui na Google Play Store  ",
    invitacionapp1M: "Compartilhar",
    registrarse1M: "Inscrever-se",
    tengocuentaM: "eu já tenho uma conta"
}

export { en, es, hi, zh, pt }